dbc_overflow_kelsey/config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :answers
  end

end

dbc_overflow_kelsey/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

dbc_overflow_kelsey/app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  validates :title, presence: true,
                    length: { minimum: 5 }
end

dbc_overflow_kelsey/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    # @answer = @question.answers.create(answer_params)
    @answer = @question.answers.new(answer_params)
    if @question.save
      redirect_to @question
    else
      render 'new'
  end

  private
    def answer_params
      params.require(:answer).permit(:title, :content)
    end
end

dbc_overflow_kelsey/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

dbc_overflow_kelsey/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path
  end


  private
    def question_params
      params.require(:question).permit(:title, :content)
    end
end

dbc_overflow_kelsey/app/helpers/answers_helper.rb
module AnswersHelper
end

dbc_overflow_kelsey/app/helpers/application_helper.rb
module ApplicationHelper
end

dbc_overflow_kelsey/app/helpers/questions_helper.rb
module QuestionsHelper
end

dbc_overflow_kelsey/app/views/answers/new.html.erb
<%= link_to 'Back', questions_path %>

dbc_overflow_kelsey/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbcOverflowKelsey</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

dbc_overflow_kelsey/app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= form_for :question, url: question_path(@question), method: :patch do |f| %>

   <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %>
        prohibited this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to 'Back', questions_path %>

dbc_overflow_kelsey/app/views/questions/index.html.erb
<h1>Listing Questions</h1>

<div class="all_questions">
  <% @questions.each do |question| %>
  <div class="question">
    Title: <%= question.title %>
    Context: <%= question.content %>

    <%= link_to 'Back', questions_path %>
    <%= link_to 'Edit', edit_question_path(question) %>
    <%= link_to 'Delete', question_path(question),
        method: :delete,
        data: { confirm: 'Are you sure?'} %>
  </div>
  <% end %>
</div>

dbc_overflow_kelsey/app/views/questions/new.html.erb
<h1>New Question!</h1>


<%= form_for :question, url: questions_path do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %>
        prohibited this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to 'Back', questions_path %>

dbc_overflow_kelsey/app/views/questions/show.html.erb
Show page!

<p>
  Title: <%= @question.title %>
</p>

<p>
  Content: <%= @question.content %>
</p>

<%= link_to 'Back', questions_path %>
<%= link_to 'Edit', edit_question_path(@question) %>
<%= link_to 'Delete', question_path(@question),
    method: :delete,
    data: { confirm: 'Are you sure?'} %>